# Generated by Django 4.1.7 on 2023-03-20 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Рисунок', 'verbose_name_plural': 'Рисунки'},
        ),
        migrations.AddField(
            model_name='pictures',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Уникальное название картины'),
            preserve_default=False,
        ),
    ]
