# Generated by Django 4.1.7 on 2023-03-20 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_pictures_options_pictures_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 3, 20, 12, 59, 41, 160659, tzinfo=datetime.timezone.utc), unique=True, verbose_name='Уникальное название картины'),
        ),
    ]
