# Generated by Django 4.1.7 on 2023-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_pictures_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальное название картины'),
        ),
    ]
