# Generated by Django 4.1.7 on 2023-03-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_account_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
