# Generated by Django 4.1.7 on 2023-04-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
